default_platform(:ios)

platform :ios do
  desc "Set up certificates"
  lane :certificate_setup do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_filepath: options[:key_filepath]
    )
    cert(
      api_key: api_key,
      keychain_path: options[:keychain_path],
      keychain_password: options[:keychain_password]
    )
    sigh(
      api_key: @api_key,
      readonly: 'true'
    )
  end
  desc "Release to iOS Store"
  lane :release do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_filepath: options[:key_filepath]
      )
      upload_to_testflight(
        ipa: options[:ipa_path],
        api_key: api_key
      )
      # upload_to_app_store
  end
end

platform :android do
  desc "Release to Google Play Store"
  lane :release do |options|
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      aab: options[:aab_path]
    )
  end
end