name: "Android App Workflow"

on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Run test
        run: |
          yarn test
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
