name: "Android App Workflow"

on:
  pull_request:
  push:

env:
  SONAR_HOST: 'https://sonarqube.services.liatr.io'

jobs:
  setup:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node modules
        run: |
          yarn install
      - name: Test
        run: |
          yarn test
      - name: SonarQube Scan
        uses: docker://sonarsource/sonar-scanner-cli:4.6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_SHAREDSVC_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST }}
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_SHAREDSVC_TOKEN }}
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon
