name: "Android App Workflow"

# on:
#   pull_request:
#   push:

# env:
#   ARTIFACT_NAME: ghcr.io/${{ github.repository_owner }}/mobile-pipeline-poc
#   GIHUB_REPO: liatrio/mobile-pipeline-poc

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install node modules
        run: |
          yarn install
      - name: Run test
        run: |
          yarn test
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      # - name: Generate tag
      #   id: tag
      #   run: |
      #     echo ::set-output name=TAG::$(jq -r .version package.json)
      #     echo ::set-output name=SOURCE_TAG::$(git describe --tags --abbrev=0)
      # - name: Bump version check
      #   run: |
      #     if [ ${{ steps.tag.outputs.TAG }} == ${{ steps.tag.outputs.SOURCE_TAG }} ]; then
      #       echo "Version: ${{ steps.tag.outputs.TAG }} needs to be updated in package.json" 
      #       exit 1
      #     fi 
      # - name: Create release
      #   uses: liatrio/github-actions/github-release@github-release-package-actions
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     owner: 'liatrio'
      #     repo: 'mobile-pipeline-poc'
      #     tag_name: ${{ steps.tag.output.TAG }}
      #     name: 'Testing release action'
      #     token_name: 'token'
      #     pat: ${{ secrets.GITHUB_TOKEN }}

      # - name: Deploy Android binary to Github Packages
      #   uses: liatrio/github-actions/github-package@github-release-package-actions
      #   with: 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     FILE: 'ReactNativeSemaphoreNew.xcarchive/Products/Applications/ReactNativeSemaphoreNew.app'
      #     GITHUB_REPOSITORY: ${{ env.GITHUB_REPO }}
