name: "Appium Workflow"

on:
  pull_request: 
  push:

jobs:
  Appium:
    runs-on: macos-latest
    env:
      JAVA_HOME: '/Library/Java/JavaVirtualMachines/Adopt-11.jdk/Contents/Home'
    strategy:
      matrix:
        sdk: [28, 29, 30]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Install Yarn
        run: brew install yarn

      - name: Install node modules
        run: yarn install

      ### Android

      - name: Setup android SDK
        uses: android-actions/setup-android@v2
      - name: Platform tools installation
        run: sdkmanager "platform-tools" "platforms;android-${{matrix.sdk}}"

      - name: List sdks
        run: sdkmanager --list | grep system-images

      - name: Install Emulator SDK
        run: sdkmanager --install emulator
      - name: Install SDK
        run: sdkmanager --install "system-images;android-${{matrix.sdk}};google_apis;x86"
      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-${{matrix.sdk}};google_apis;x86"

      ### iOS

      - name: Install Ruby
        run: brew install ruby
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Check Xcode Version
        run: xcodebuild -version

      - run: xcode-select -p
      - name: Install Pod dependencies
        run: pod install
        working-directory: ios

      ### Both

      - name: Run appium-doctor        
        run: npm run appium-doctor
      # - name: Run appium in the background        
      #   run: npm run appium &
      # - name: Check appium server status        
      #   run: curl http://localhost:4723/wd/hub/status

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      