name: "Appium Workflow"

on:
  pull_request: 
  push:

jobs:
  Appium:
    runs-on: macos-latest
    env:
      ANDROID_SDK_ROOT: '/Users/runner/Library/Android/sdk'
      ANDROID_HOME: '/Users/runner/Library/Android/sdk'
    strategy:
      matrix:
        sdk: [28]
        target: [default]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Install Yarn
        run: brew install yarn

      - name: Install node modules
        run: yarn install

      - name: Run appium-doctor        
        run: npm run appium-doctor
      - name: Run appium in the background        
        run: npm run appium &
      - name: Check appium server status        
        run: curl http://localhost:4723/wd/hub/status

     ### Android sdk

      - name: Setup android SDK
        uses: android-actions/setup-android@v2
      - name: Platform tools installation
        run: sdkmanager "platform-tools" "platforms;android-${{matrix.sdk}}"

      - name: List sdks
        run: sdkmanager --list | grep system-images

      - name: Install Emulator SDK
        run: sdkmanager --install emulator
      - name: Install SDK
        run: sdkmanager --install "system-images;android-${{matrix.sdk}};google_apis;x86"
      - name: Create AVD
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-${{matrix.sdk}};google_apis;x86"


      ## Android abd
      - name: Setup adb server
        run: sudo adb devices && adb start-server &

      - name: Run emulator
        run: cd /Users/runner/Library/Android/sdk/emulator && ./emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &

      - name: Run appium integration Tests
        run: |
          cd Appium
          adb shell settings put global hidden_api_policy_pre_p_apps  1
          adb shell settings put global hidden_api_policy_p_apps 1
          $(npm bin)/mocha .