name: "Appium Workflow"

on:
  pull_request: 
  push:

jobs:
  Appium:
    runs-on: macos-latest
    env:
      ANDROID_SDK_ROOT: '/Users/runner/Library/Android/sdk'
      ANDROID_HOME: '/Users/runner/Library/Android/sdk'
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Test yarn
        uses: yarn install