name: "Appium Workflow"

on:
  pull_request: 
  push:

jobs:
  Appium_IOS:
    runs-on: macos-latest
    env:
      ANDROID_SDK_ROOT: '/Users/runner/Library/Android/sdk'
      ANDROID_HOME: '/Users/runner/Library/Android/sdk'
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Install node modules
        run: yarn install

      - run: xcode-select -p
      - name: Install Pod dependencies
        run: pod install
        working-directory: ios

      ## Setup appium  
      - name: Run appium-doctor        
        run: npm run appium-doctor
      - name: Run appium in the background        
        run: npm run appium &
      - name: Check appium server status        
        run: curl http://localhost:4723/wd/hub/status

        # xcodebuild clean test -project ios/ReactNativeSemaphoreNew.xcodeproj -scheme ReactNativeSemaphoreNew -destination "platform=iOS Simulator,name=iPhone 11 Pro"

      - name: Boot iOS simulator
        run: xcrun simctl boot "iPhone 11" &

      - name: Build IOS
        # run: xcodebuild -workspace ios/ReactNativeSemaphoreNew.xcworkspace -scheme ReactNativeSemaphoreNew clean archive -sdk iphoneos15.0 -configuration release -UseModernBuildSystem=NO -archivePath $PWD/ReactNativeSemaphoreNew.xcarchive CODE_SIGNING_ALLOWED=NO
        run: xcodebuild -workspace ios/ReactNativeSemaphoreNew.xcworkspace -scheme ReactNativeSemaphoreNew clean archive -destination "platform=iOS Simulator,name=iPhone 11" -configuration release -UseModernBuildSystem=NO -archivePath $PWD/ReactNativeSemaphoreNew.xcarchive CODE_SIGNING_ALLOWED=NO
        # -destination "platform=iOS Simulator,name=iPhone SE"

      - name: Check simulator status
        run: xcrun simctl list | grep "(Booted)"
        
      # run: xcodebuild -workspace ios/ReactNativeSemaphoreNew.xcworkspace -scheme ReactNativeSemaphoreNew clean archive -sdk iphoneos -configuration release -UseModernBuildSystem=NO -archivePath $PWD/ReactNativeSemaphoreNew.xcarchive CODE_SIGNING_ALLOWED=NO


      # - name: 'upload artifact to be used with other jobs'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: 'ReactNativeSemaphoreNew.app'
      #     path: 'ReactNativeSemaphoreNew.xcarchive/Products/Applications/ReactNativeSemaphoreNew.app'
      # - name: Convert the app's .app file to .ipa
      #   run: |
      #     mkdir Payload
      #     cp -R ReactNativeSemaphoreNew.xcarchive/Products/Applications/ReactNativeSemaphoreNew.app Payload 
      #     zip -r ReactNativeSemaphoreNew.ipa Payload

      # - name: Run the emulator in the background
      #   run: |
      #     /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID ADDCA261-95B1-41D4-B911-FCBD965EDBF2 &

  #     - name: Run appium integration Tests
  #       run: npm run mocha appium/ios

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1 
        
  # Appium:
  #   runs-on: macos-latest
  #   env:
  #     ANDROID_SDK_ROOT: '/Users/runner/Library/Android/sdk'
  #     ANDROID_HOME: '/Users/runner/Library/Android/sdk'
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v2

  #     - name: Set up JDK 8
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: '8'

  #     - name: Install node modules
  #       run: yarn install

  #     ## Setup appium  
  #     - name: Run appium-doctor        
  #       run: npm run appium-doctor
  #     - name: Run appium in the background        
  #       run: npm run appium &
  #     - name: Check appium server status        
  #       run: curl http://localhost:4723/wd/hub/status

  #     ## Android sdk
  #     - name: Setup android SDK
  #       uses: android-actions/setup-android@v2
  #     - name: Platform tools installation
  #       run: sdkmanager "platform-tools" "platforms;android-27"

  #     ## Android emulator creation
  #     - name: Install SDK
  #       run: sdkmanager --install "system-images;android-27;google_apis;x86"
  #     - name: Create AVD
  #       run: echo "no" | avdmanager create avd -n sdk_gphone_x86 -k "system-images;android-27;google_apis;x86"

  #     ## Android abd server
  #     - name: Start adb server
  #       run: sudo adb start-server &

  #     ## Setup android emulator
  #     - name: Run emulator
  #       run: cd /Users/runner/Library/Android/sdk/emulator && ./emulator -avd sdk_gphone_x86 -no-audio -no-window -gpu swiftshader_indirect &
  #     - name: Wait for device to be operational
  #       run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

  #     - name: Run appium integration Tests
  #       run: npm run mocha appium/android
