name: "IOS App Workflow"

on:
  pull_request: 
  push:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Install Yarn
        run: brew install yarn
      - name: Install Node Modules
        run: yarn install
      - name: Install Ruby
        run: brew install ruby
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Check Xcode Version
        run: xcodebuild -version
