name: "IOS App Workflow"

on:
  pull_request: 
  push:


jobs:
  Build-and-Publish:
    runs-on: macos-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      # - name: Install Yarn
      #   run: brew install yarn
      # - name: Install Node Modules
      #   run: yarn install
      # - name: Install Ruby
      #   run: brew install ruby
      # - name: Install Cocoapods
      #   run: gem install cocoapods

      # - name: Check Xcode Version
      #   run: xcodebuild -version
      # - run: xcode-select -p
      # - run: pod install
      #   working-directory: ios
      #   name: Install Pod dependencies
      # - name: Run Tests
      #   run: yarn test
      # - name: Build IOS
      #   run: "xcodebuild \
      #   -workspace ios/ReactNativeSemaphoreNew.xcworkspace \
      #   -scheme ReactNativeSemaphoreNew \
      #   clean archive \
      #   -sdk iphoneos \
      #   -configuration release \
      #   -UseModernBuildSystem=NO \
      #   -archivePath $PWD/ReactNativeSemaphoreNew \
      #   CODE_SIGNING_ALLOWED=NO"
      
      - name: Generate tag
        id: tag
        run: |
          echo ::set-output name=tag::$(jq -r .version package.json)
          echo ::set-output name=gitTag::$(git describe --tags --match v*.*.* --abbrev=0)
      - name: Bump version check
        run: |
          if [ ${{ steps.tag.outputs.tag }} == ${{ steps.tag.outputs.gitTag }} ]; then exit 1
          fi
      # - name: Create release
      #   uses: liatrio/github-actions/github-release@github-release-package-actions
      #   if: github.ref == 'refs/heads/main'
      #   with:
      #     owner: 'liatrio'
      #     repo: 'mobile-pipeline-poc'
      #     tag_name: ${{ steps.tag.output.tag }}
      #     name: 'Testing release action'
      #     token_name: 'token'
      #     pat: ${{ secrets.GITHUB_TOKEN }}

